/* config-breeze.h. Generated by cmake from config-breeze.h.cmake */

/*
 * SPDX-FileCopyrightText: 2014 Hugo Pereira Da Costa <hugo.pereira@free.fr>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef config_breeze_h
#define config_breeze_h

/* Define to 1 if QtQuick is available */
#define BREEZE_HAVE_QTQUICK 0

/* Define to 1 if QtX11Extras is available */
#define BREEZE_HAVE_QTX11EXTRAS 0

/* Define to 1 if FrameworkIntegration/Kstyle libraries are found */
#define BREEZE_HAVE_KSTYLE 0

#endif
