name: Build with official Qt

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        qtVersion: ['6.8.1']
        arch: [x86_64, arm64, universal]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qtVersion }}
          host: mac
          target: desktop
          arch: clang_64
          archives: qtbase qtsvg qttools qttranslations

      - name: Build
        run: |
          ./packages/official-qt/macos/build.sh \
            --arch ${{ matrix.arch }} \
            --qt-install-dir $RUNNER_WORKSPACE/Qt \
            --qt-version ${{ matrix.qtVersion }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: macOS Qt ${{ matrix.qtVersion }} ${{ matrix.arch }}
          path: dist/*.tar.xz
