name: Unit

on: [push, pull_request]

jobs:
  ubuntu_makefile_escape:
    name: Unix makefile escape
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '2.8.6'

      - name: Setup Qt
        uses: ConorMacBride/install-package@v1
        with:
          apt: libqt5svg5-dev qtbase5-dev qtbase5-dev-tools qttools5-dev-tools

      - name: Build
        run: |
          xmake f --qt=/usr
          xmake b test-escape

      - name: Test
        run: |
          export QT_ASSUME_STDERR_HAS_CONSOLE=1
          xmake r test-escape

  generated_code_consistency_addon:
    name: "Generated code consistency: add-on"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ConorMacBride/install-package@v1
        with:
          apt: luarocks

      - name: Install Teal
        run: |
          sudo luarocks install tl

      - name: Build
        run: |
          ./addon/gen.sh

      - name: Check
        run: |
          git diff --color --exit-code

  imported_code_consistency_lua:
    name: "Imported code consistency: Lua"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Lua
        uses: actions/checkout@v4
        with:
          repository: lua/lua
          ref: v5.4.6
          path: lua
          fetch-depth: 1

      - name: Check
        run: |
          cd lua
          find .                                         \
            -regextype egrep                             \
            '(' -regex '.*\.(c|h|hpp)$' -a               \
              -not -path './testes/*' -a                 \
              -not -name 'ltests.*' -a                   \
              -not -name onelua.c ')'                    \
            -exec echo checking {} ';'                   \
            -exec diff --color {} ../libs/lua/lua/{} ';'
